### ISSUE TITLE
Shortcode not returning anything for Form 7

### ISSUE THREAD

**Issue by pymander** [pymander/wordpress-openpgp#2]
(Submitted by email)

There seems to be a bug in OpenPGP plugin, the shortcode in Form 7 doesn't output anything.

```javascript
function openpgp_cryptbutton_wpcf7 ($tag) {
	if (!is_array($tag)) return '';
```

It looks like newer versions of form 7 return an object,
removing the array check fixes it.

**Comment by rev138** [comment]
Thanks for the fix @pymander. Commenting out the conditional worked for me as well.

Do you have any plans for releasing a patched version?
